services:

  typescript:
    build: 
      context: .
      dockerfile: Dockerfile.typescript
    volumes:
      - ../typescript:/workspace/typescript:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ../python:/workspace/python:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    volumes:
      - ../golang:/workspace/golang:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  java:
    build:
      context: .
      dockerfile: Dockerfile.java
    volumes:
      - ../java:/workspace/java:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  mongo-database:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

# Uncomment to run sample data import.
  init-db:
    build: 
      context: .
      dockerfile: Dockerfile.mongodb-data
    depends_on:
      - mongo-database

volumes:
  mongodb-data:
