services:

  typescript:
    build: 
      context: .
      dockerfile: Dockerfile.typescript
    volumes:
      - ../typescript:/workspace/typescript:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ../python:/workspace/python:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongo-database

  mongo-database:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    
  init-db:
    build: 
      context: .
      dockerfile: Dockerfile.mongodb-data
 #   volumes:
 #     - ../sample_data:/workspace/sample_data:ro
 #   command: /bin/sh -c "sleep 10 && /workspace/load_sample_data.sh"
    depends_on:
      - mongo-database

volumes:
  mongodb-data: